services:
  - type: web
    name: staff-planner-api
    env: node
    buildCommand: cd server && npm install
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false

  - type: static
    name: staff-planner-frontend
    buildCommand: cd client && npm install && npm run build
    publishDir: client/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: staff-planner-api
          type: web
          property: url
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 